baseURL = 'https://kevinkle.in/'
languageCode = 'en-us'
title = 'Blog'
theme = "archie"
paginate = 50
copyright = "© Kevin Klein"
staticDir = "static"
googleAnalytics = "G-SGRSG6Y0WX"

[params]
favicon = "img/favicon.ico"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/kklein"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/kevkle"

[[menu.main]]
name = "Hello"
url = "/about"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3